name: Feo Tensor CI

on:
  pull_request: {}
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: "./.github/workflows/lint.yml"

  test:
    name: Test
    uses: "./.github/workflows/test.yml"

  release:
    name: Release
    needs:
      - lint
      - test
    uses: "./.github/workflows/release.yml"

  publish:
    name: Publish
    needs: release
    uses: "./.github/workflows/publish.yml"
    with:
      new_release_published: ${{ needs.release.outputs.new_release_published }}
      new_release_version: ${{ needs.release.outputs.new_release_version }}
