name: Lint

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  lint-rust:
    name: Rust Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

  lint-commits:
    name: Commit Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint
        run: npm install --save-dev @commitlint/{cli,config-conventional}

      - name: Commitlint (PR)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }}

      - name: Commitlint (Push)
        if: github.event_name == 'push'
        run: npx commitlint --from ${{ github.event.before }}
